apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring-boot-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/spring-boot-persistent-volume"