apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-mongodb
spec:
  selector:
    matchLabels:
      database: graylog-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        database: graylog-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-mongodb
spec:
  selector:
    database: graylog-mongodb
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017

