apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-elastic-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-elastic-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/graylog/elasticsearch/data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-elasticsearch
spec:
  selector:
    matchLabels:
      service: graylog-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        service: graylog-elasticsearch
    spec:
      containers:
      - name: graylog-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: graylog-elastic-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-elasticsearch
spec:
  type: NodePort
  selector:
    service: graylog-elasticsearch
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30001
  - name: "9300"
    port: 9300
    targetPort: 9300
    nodePort: 30002