spring:
  application:
    name: "spring-boot-app"

info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: "@project.build.sourceEncoding@"
  application.name: ${spring.application.name}
  spring.boot.version: "@project.parent.version@"
  
# Expose all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"  
